<?php

namespace App\Observers;

use App\Models\User;
use App\Models\Role;
use Illuminate\Support\Facades\Log;

class UserObserver
{
    /**
     * Handle the User "created" event.
     */
    public function created(User $user): void
    {
        // Auto-generate documents based on user role
        $this->autoGenerateDocuments($user);
    }

    /**
     * Handle the User "updated" event.
     */
    public function updated(User $user): void
    {
        // Check if role was changed and regenerate documents if needed
        if ($user->wasChanged('primary_role_id')) {
            $this->autoGenerateDocuments($user);
        }
    }

    /**
     * Auto-generate documents for the user
     */
    private function autoGenerateDocuments(User $user): void
    {
        try {
            // Get user's primary role
            $role = $user->roles()->first();
            
            if (!$role) {
                return;
            }

            $roleName = strtolower($role->name);

            switch ($roleName) {
                case 'student':
                    $this->generateStudentDocuments($user);
                    break;
                case 'teacher':
                case 'staff':
                case 'admin':
                    $this->generateStaffDocuments($user);
                    break;
            }

            Log::info("Auto-generated documents for user: {$user->name} ({$user->email})");
        } catch (\Exception $e) {
            Log::error("Failed to auto-generate documents for user {$user->id}: " . $e->getMessage());
        }
    }

    /**
     * Generate student-specific documents
     */
    private function generateStudentDocuments(User $user): void
    {
        // Generate Student ID Card
        $this->generateStudentIdCard($user);
        
        // Generate Library Card
        $this->generateLibraryCard($user);
    }

    /**
     * Generate staff-specific documents
     */
    private function generateStaffDocuments(User $user): void
    {
        // Generate Staff ID Card
        $this->generateStaffIdCard($user);
    }

    /**
     * Generate Student ID Card
     */
    private function generateStudentIdCard(User $user): void
    {
        try {
            $student = \Modules\Academic\Models\Student::where('user_id', $user->id)->first();
            
            if ($student) {
                // Store the document generation request in a queue or log
                Log::info("Auto-generate Student ID Card for: {$user->name}");
                
                // You can also trigger an Artisan command here
                // \Artisan::call('documents:generate-student-id', ['student_id' => $student->id]);
            }
        } catch (\Exception $e) {
            Log::error("Failed to generate Student ID Card for user {$user->id}: " . $e->getMessage());
        }
    }

    /**
     * Generate Library Card
     */
    private function generateLibraryCard(User $user): void
    {
        try {
            $student = \Modules\Academic\Models\Student::where('user_id', $user->id)->first();
            
            if ($student) {
                Log::info("Auto-generate Library Card for: {$user->name}");
                
                // You can also trigger an Artisan command here
                // \Artisan::call('documents:generate-library-card', ['student_id' => $student->id]);
            }
        } catch (\Exception $e) {
            Log::error("Failed to generate Library Card for user {$user->id}: " . $e->getMessage());
        }
    }

    /**
     * Generate Staff ID Card
     */
    private function generateStaffIdCard(User $user): void
    {
        try {
            Log::info("Auto-generate Staff ID Card for: {$user->name}");
            
            // You can also trigger an Artisan command here
            // \Artisan::call('documents:generate-staff-id', ['user_id' => $user->id]);
        } catch (\Exception $e) {
            Log::error("Failed to generate Staff ID Card for user {$user->id}: " . $e->getMessage());
        }
    }
}
