<?php

use Illuminate\Support\Facades\Route;
use Modules\Timetable\Http\Controllers\TimetableController;
use Modules\Timetable\Http\Controllers\RoomController;
use Modules\Timetable\Http\Controllers\TeacherAvailabilityController;
use Modules\Timetable\Http\Controllers\RoomAllocationController;
use Modules\Timetable\Http\Controllers\ClassScheduleController;
use Modules\Timetable\Http\Controllers\RoomAvailabilityController;

// Test route without authentication
Route::get('timetables/test', function () {
    return 'Timetable module is working!';
})->name('timetables.test');

// Test route for TimetableController without authentication
Route::get('timetables/test-controller', function () {
    try {
        $controller = new \Modules\Timetable\Http\Controllers\TimetableController();
        return $controller->index();
    } catch (\Exception $e) {
        return response()->json([
            'error' => $e->getMessage(),
            'file' => $e->getFile(),
            'line' => $e->getLine()
        ], 500);
    }
})->name('timetables.test-controller');

// Simple test route that returns JSON data
Route::get('timetables/test-data', function () {
    try {
        $controller = new \Modules\Timetable\Http\Controllers\TimetableController();
        
        // Call the index method but capture the data instead of rendering view
        $totalSchedules = 0;
        $totalRooms = 0;
        $totalAllocations = 0;
        $totalTeachers = 0;
        $conflicts = 0;
        $availableTeachers = 0;
        $unavailableTeachers = 0;
        $upcomingSchedules = collect();
        $status = 'not_configured';

        if (\Illuminate\Support\Facades\Schema::hasTable('class_schedules')) {
            $totalSchedules = \Modules\Timetable\Models\ClassSchedule::count();
        }
        if (\Illuminate\Support\Facades\Schema::hasTable('rooms')) {
            $totalRooms = \Modules\Timetable\Models\Room::count();
        }
        if (\Illuminate\Support\Facades\Schema::hasTable('room_allocations')) {
            $totalAllocations = \Modules\Timetable\Models\RoomAllocation::count();
        }
        if (\Illuminate\Support\Facades\Schema::hasTable('teachers')) {
            try {
                $totalTeachers = \App\Models\Teacher::count();
            } catch (\Exception $e) {
                $totalTeachers = 0;
            }
        }

        return response()->json([
            'success' => true,
            'data' => [
                'totalSchedules' => $totalSchedules,
                'totalRooms' => $totalRooms,
                'totalAllocations' => $totalAllocations,
                'totalTeachers' => $totalTeachers,
                'conflicts' => $conflicts,
                'availableTeachers' => $availableTeachers,
                'unavailableTeachers' => $unavailableTeachers,
                'status' => $status
            ]
        ]);
    } catch (\Exception $e) {
        return response()->json([
            'error' => $e->getMessage(),
            'file' => $e->getFile(),
            'line' => $e->getLine()
        ], 500);
    }
})->name('timetables.test-data');

// Test route for calendar method
Route::get('timetables/test-calendar', function () {
    try {
        $controller = new \Modules\Timetable\Http\Controllers\TimetableController();
        
        // Test the calendar method logic without rendering view
        if (\Illuminate\Support\Facades\Schema::hasTable('timetables')) {
            $timetables = \App\Models\Modules\Timetable\Models\Timetable::all();
        } else {
            $timetables = collect();
        }
        
        return response()->json([
            'success' => true,
            'timetables_count' => $timetables->count(),
            'message' => 'Calendar method working correctly'
        ]);
    } catch (\Exception $e) {
        return response()->json([
            'error' => $e->getMessage(),
            'file' => $e->getFile(),
            'line' => $e->getLine()
        ], 500);
    }
})->name('timetables.test-calendar');

Route::middleware(['web', 'auth'])->group(function () {
    Route::get('timetables/dashboard', [TimetableController::class, 'index'])->name('timetables.dashboard');
    Route::resource('timetables', TimetableController::class)->names('timetables');
    Route::post('timetables/autogenerate', [TimetableController::class, 'autoGenerate'])->name('timetables.autogenerate');
    Route::post('timetables/autogenerate/save', [TimetableController::class, 'saveAutoGenerated'])->name('timetables.autogenerate.save');
    Route::resource('rooms', RoomController::class)->names('rooms');
    Route::get('rooms/export/csv', [RoomController::class, 'exportCsv'])->name('rooms.export.csv');
    Route::get('rooms/export/pdf', [RoomController::class, 'exportPdf'])->name('rooms.export.pdf');
    Route::resource('teacher-availabilities', TeacherAvailabilityController::class)->names('teacher_availabilities');
    Route::resource('room-availabilities', RoomAvailabilityController::class)->names('room_availabilities');
    Route::get('room-availabilities/export/csv', [RoomAvailabilityController::class, 'exportCsv'])->name('room_availabilities.export.csv');
    Route::get('room-availabilities/export/pdf', [RoomAvailabilityController::class, 'exportPdf'])->name('room_availabilities.export.pdf');
    Route::resource('room-allocations', RoomAllocationController::class)->names('room_allocations');
    Route::get('room-allocations/export/csv', [RoomAllocationController::class, 'exportCsv'])->name('room_allocations.export.csv');
    Route::get('room-allocations/export/pdf', [RoomAllocationController::class, 'exportPdf'])->name('room_allocations.export.pdf');
    Route::get('calendar', [TimetableController::class, 'calendar'])->name('timetable.calendar');
    Route::get('calendar/data', [TimetableController::class, 'calendarData'])->name('timetable.calendar.data');
    Route::get('timetables/print', [TimetableController::class, 'print'])->name('timetables.print');
    Route::get('timetables/reports', [TimetableController::class, 'reports'])->name('timetables.reports');
    Route::get('timetable/conflicts', [TimetableController::class, 'conflicts'])->name('timetable.conflicts');
    Route::get('timetable/analytics', [TimetableController::class, 'analytics'])->name('timetable.analytics');
    Route::get('timetables/settings', [TimetableController::class, 'settings'])->name('timetables.settings');
    Route::resource('class-schedules', ClassScheduleController::class)->names('class_schedules');
    Route::get('timetable/class-schedules', [ClassScheduleController::class, 'index'])->name('timetable.class_schedules');
    Route::post('class-schedules/export/pdf', [ClassScheduleController::class, 'exportPdf'])->name('class_schedules.export.pdf');
    // Timetable workflow routes
    Route::post('timetables/{id}/submit', [TimetableController::class, 'submitForApproval'])->name('timetables.submit');
    Route::post('timetables/{id}/approve', [TimetableController::class, 'approve'])->name('timetables.approve');
    Route::post('timetables/{id}/reject', [TimetableController::class, 'reject'])->name('timetables.reject');
    Route::post('timetables/{id}/publish', [TimetableController::class, 'publish'])->name('timetables.publish');
    Route::post('timetables/{id}/archive', [TimetableController::class, 'archive'])->name('timetables.archive');
    
    // Add missing routes
    Route::get('timetable/settings', [TimetableController::class, 'settings'])->name('timetable.settings');
});

