<?php

use Illuminate\Support\Facades\Route;
use Modules\Timetable\Http\Controllers\TimetableController;
use Modules\Timetable\Http\Controllers\RoomController;
use Modules\Timetable\Http\Controllers\TeacherAvailabilityController;
use Modules\Timetable\Http\Controllers\RoomAllocationController;
use Modules\Timetable\Http\Controllers\ClassScheduleController;

Route::middleware(['web', 'auth'])->group(function () {
    Route::get('timetables/dashboard', [\Modules\Timetable\Http\Controllers\TimetableController::class, 'index'])->name('timetables.dashboard');
    Route::resource('timetables', \App\Http\Controllers\Modules\Timetable\Http\Controllers\TimetableManagementController::class)->names('timetables');
    Route::post('timetables/autogenerate', [TimetableController::class, 'autoGenerate'])->name('timetables.autogenerate');
    Route::post('timetables/autogenerate/save', [TimetableController::class, 'saveAutoGenerated'])->name('timetables.autogenerate.save');
    Route::resource('rooms', RoomController::class)->names('rooms');
    Route::resource('teacher-availabilities', TeacherAvailabilityController::class)->names('teacher_availabilities');
    Route::resource('room-allocations', RoomAllocationController::class)->names('room_allocations');
    Route::get('room-allocations', [\Modules\Timetable\Http\Controllers\RoomAllocationController::class, 'index'])->name('room_allocations.index');
    Route::resource('room-availabilities', \App\Http\Controllers\Modules\Timetable\Http\Controllers\RoomAvailabilityController::class)->names('room_availabilities');
    Route::get('calendar', [\Modules\Timetable\Http\Controllers\TimetableController::class, 'calendar'])->name('timetable.calendar');
    Route::get('calendar/data', [\Modules\Timetable\Http\Controllers\TimetableController::class, 'calendarData'])->name('timetable.calendar.data');
    Route::get('timetables/print', [TimetableController::class, 'print'])->name('timetables.print');
    Route::get('timetables/reports', [TimetableController::class, 'reports'])->name('timetables.reports');
    Route::get('timetable/conflicts', [TimetableController::class, 'conflicts'])->name('timetable.conflicts');
    Route::get('timetable/analytics', [TimetableController::class, 'analytics'])->name('timetable.analytics');
    Route::get('timetables/settings', [TimetableController::class, 'settings'])->name('timetables.settings');
    Route::resource('class-schedules', ClassScheduleController::class)->names('class_schedules');
    Route::get('timetable/class-schedules', [\Modules\Timetable\Http\Controllers\ClassScheduleController::class, 'index'])->name('timetable.class_schedules');
    // Timetable workflow routes
    Route::post('timetables/{id}/submit', [\App\Http\Controllers\Modules\Timetable\Http\Controllers\TimetableManagementController::class, 'submitForApproval'])->name('timetables.submit');
    Route::post('timetables/{id}/approve', [\App\Http\Controllers\Modules\Timetable\Http\Controllers\TimetableManagementController::class, 'approve'])->name('timetables.approve');
    Route::post('timetables/{id}/reject', [\App\Http\Controllers\Modules\Timetable\Http\Controllers\TimetableManagementController::class, 'reject'])->name('timetables.reject');
    Route::post('timetables/{id}/publish', [\App\Http\Controllers\Modules\Timetable\Http\Controllers\TimetableManagementController::class, 'publish'])->name('timetables.publish');
    Route::post('timetables/{id}/archive', [\App\Http\Controllers\Modules\Timetable\Http\Controllers\TimetableManagementController::class, 'archive'])->name('timetables.archive');
});
